server:
  port: 9091
  forward-headers-strategy: framework

spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3308/testdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: test
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379